telegram_bot:
  tg_endpoint: 'https://api.telegram.org'
  token: ''

auth_cfg:
  id:
  username: ''
  first_name: ''
  last_name: ''

torrents:
  transmission_ip: 'http://127.0.0.1'
  transmission_port: 9091
  files_dir: 'files'
  t_file_magnet: 'config/torrent.pcl'
  t_username: ''
  t_password: ''

# Favourites folders
# i.e. F1 - alias that will be used in set command
# e.g. If you send the next command to the bot:
# set F1
# then /mnt/HDD/Plex/Movies directory will be used
# as a default directory for all next downloads
favourites:
  Downloads: '/home/pi/Downloads'
  Videos: '/home/pi/Videos'
  HDDStorage: ''